apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  selector:
    matchLabels:
      env: development
  template:
      metadata:
        name: nginx
        labels:
          app: nginx
          type: frontend
          env: development
      spec:
        containers:
          - name: nginx
            image: nginx
  replicas: 3